import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import ReactFlow, { Background, Controls, MiniMap, type Edge, type Node } from 'reactflow';
import 'reactflow/dist/style.css';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Bell, Bot, Code2, FileText, GitBranch, LayoutDashboard, Network, Search, Settings, ShieldAlert, Sparkles } from 'lucide-react';
import { api, type ChatAnswer, type RepositoryOverview, type SecurityFinding } from './lib/api';
import { useAppStore } from './lib/store';
import './styles.css';

const nav = ['Dashboard','Repositories','Repository Chat','Architecture','Dependency Graph','Security Analysis','Code Quality','Impact Analysis','Documentation','Settings'];
const icons = [LayoutDashboard, GitBranch, Bot, Network, Code2, ShieldAlert, Sparkles, GitBranch, FileText, Settings];
function Shell(){ const [page,setPage]=useState(nav[0]); return <div className="app"><aside><div className="brand"><Sparkles/>FLIFo ACIA</div>{nav.map((n,i)=>{const Icon=icons[i];return <button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><Icon size={18}/>{n}</button>})}</aside><main><header><div><p>Project Name</p><h1>{page}</h1></div><label className="search"><Search size={16}/><input placeholder="Search repositories, files, functions"/></label><Bell/><div className="avatar">AI</div></header><Page page={page}/></main></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="card metric"><p>{label}</p><strong>{value}</strong></div>}
function Dashboard(){ const scores=[{name:'Security',score:88},{name:'Maintainability',score:82},{name:'Documentation',score:74},{name:'Testing',score:67}]; const radar=[{subject:'Security',A:88},{subject:'Maintainability',A:82},{subject:'Performance',A:79},{subject:'Documentation',A:74},{subject:'Testing',A:67}]; return <section><div className="grid five"><Metric label="Total Repositories" value="24"/><Metric label="Total Files" value="18.7k"/><Metric label="Security Issues" value="12"/><Metric label="Documentation Coverage" value="74%"/><Metric label="Health Score" value="82"/></div><div className="grid two"><div className="card"><h2>Engineering Scores</h2><ResponsiveContainer height={260}><BarChart data={scores}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="name" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip/><Bar dataKey="score" fill="#8b5cf6" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div><div className="card"><h2>Health Score</h2><ResponsiveContainer height={260}><RadarChart data={radar}><PolarGrid/><PolarAngleAxis dataKey="subject"/><Radar dataKey="A" stroke="#06b6d4" fill="#06b6d4" fillOpacity={0.45}/></RadarChart></ResponsiveContainer></div></div><div className="card"><h2>Recent Activity</h2>{['Indexed acia core parser','Security scan completed','Generated architecture graph','Repository chat answered JWT question'].map(x=><p className="activity" key={x}>{x}</p>)}</div></section>}
function Repositories(){ const {repoPath,setRepoPath}=useAppStore(); const [repo,setRepo]=useState<RepositoryOverview>(); return <section><div className="card"><h2>Repository Analysis</h2><div className="form"><input value={repoPath} onChange={e=>setRepoPath(e.target.value)} placeholder="GitHub URL or mounted path"/><button onClick={()=>api.analyzeLocal(repoPath).then(setRepo)}>Analyze</button></div></div>{repo&&<div className="grid two"><div className="card"><h2>{repo.repository_id}</h2><p>Languages: {repo.languages.join(', ')||'Unknown'}</p><p>Framework: {repo.frameworks.join(', ')||'Unknown'}</p><p>Architecture: {repo.architecture_pattern}</p><p>Total Files: {repo.files_indexed}</p><p>Total Classes: {repo.symbols.filter(s=>s.kind==='class').length}</p><p>Total Functions: {repo.symbols.filter(s=>s.kind==='function').length}</p></div><div className="card tree"><h2>Repository Tree</h2>{[...new Set(repo.symbols.map(s=>s.file_path))].slice(0,40).map(f=><p key={f}>▸ {f}</p>)}</div></div>}</section>}
function Chat(){ const [q,setQ]=useState('How does authentication work?'); const [answer,setAnswer]=useState<ChatAnswer>(); const repoPath=useAppStore(s=>s.repoPath); return <section className="card chat"><div className="suggestions">{['Where is JWT generated?','What APIs are exposed?','How is payment processed?'].map(x=><button onClick={()=>setQ(x)} key={x}>{x}</button>)}</div><div className="messages"><p className="assistant">Ask repository-specific questions with file, function, and code references.</p>{answer&&<p className="assistant">{answer.answer}<br/>References: {answer.citations.join(', ')}</p>}</div><div className="form"><input value={q} onChange={e=>setQ(e.target.value)}/><button onClick={()=>api.chatLocal(q,repoPath).then(setAnswer)}>Send</button></div></section>}
function FlowPage({impact=false}:{impact?:boolean}){ const [module,setModule]=useState('acia/main.py'); const nodes:Node[]=useMemo(()=> impact?[{id:'1',position:{x:0,y:80},data:{label:module}},{id:'2',position:{x:250,y:20},data:{label:'Affected APIs'}},{id:'3',position:{x:250,y:150},data:{label:'Affected Services'}}]:['Frontend','API Layer','Business Layer','Repository Layer','Database'].map((label,i)=>({id:String(i),position:{x:120,y:i*95},data:{label}})),[impact,module]); const edges:Edge[]=nodes.slice(1).map((n,i)=>({id:`e${i}`,source:impact?'1':String(i),target:n.id,animated:true})); return <section><div className="card flowbar">{impact&&<><input value={module} onChange={e=>setModule(e.target.value)}/><button>Analyze Impact</button></>}<span>Zoom, pan, and inspect graph nodes.</span></div><div className="card flow"><ReactFlow nodes={nodes} edges={edges} fitView><MiniMap/><Controls/><Background/></ReactFlow></div></section>}
function Security(){ const [items,setItems]=useState<SecurityFinding[]>([]); const repoPath=useAppStore(s=>s.repoPath); return <section><div className="card flowbar"><button onClick={()=>api.securityLocal(repoPath).then(setItems)}>Run Security Scan</button><input placeholder="Filter findings"/></div><div className="grid two">{['critical','high','medium','low'].map(sev=><div className="card" key={sev}><h2>{sev.toUpperCase()}</h2>{items.filter(i=>i.severity===sev).map(i=><p className="finding" key={`${i.file_path}${i.line}`}>{i.issue} — {i.file_path}:{i.line}<br/><small>{i.recommendation}</small></p>)}</div>)}</div></section>}
function Quality(){ const data=[{name:'Low',value:42},{name:'Medium',value:18},{name:'High',value:7}]; return <section className="grid two"><div className="card"><h2>Complexity Distribution</h2><ResponsiveContainer height={260}><AreaChart data={data}><XAxis dataKey="name"/><YAxis/><Tooltip/><Area dataKey="value" fill="#22c55e" stroke="#22c55e"/></AreaChart></ResponsiveContainer></div><div className="card"><h2>Quality Score</h2><p className="score">84</p><p>Maintainability, technical debt, and architecture violation tracking.</p></div></section>}
function Docs(){return <section className="grid two">{['README','Setup Guide','API Documentation','Developer Guide'].map(d=><div className="card doc" key={d}><h2>{d}</h2><p>Generated repository documentation preview.</p><button>Export Markdown</button></div>)}</section>}
function Page({page}:{page:string}){ if(page==='Repositories') return <Repositories/>; if(page==='Repository Chat') return <Chat/>; if(page==='Architecture'||page==='Dependency Graph') return <FlowPage/>; if(page==='Impact Analysis') return <FlowPage impact/>; if(page==='Security Analysis') return <Security/>; if(page==='Code Quality'||page==='Health Score') return <Quality/>; if(page==='Documentation') return <Docs/>; return <Dashboard/> }
createRoot(document.getElementById('root')!).render(<Shell/>);
